### Prueba inicial de Nonna

GET https://proyecto-anual-nonna-production.up.railway.app/

### Verificar API

GET http://127.0.0.1:5000/


# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------USUARIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

### Crear usuario

POST http://127.0.0.1:5000/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Juan Perez",
    "nombre_usuario": "juan_perez_test",
    "correo": "juan.perez.test@nonnatest.com",
    "clave": "123456",
    "fecha_nacimiento": "2005-05-15"
}

















# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------NEGOCIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------


































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------EMPLEO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------













































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# --------------------------------MODERACION---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------













































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------RECETA.PY---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------



































