### Prueba inicial de Nonna

GET https://proyecto-anual-nonna-production.up.railway.app/

### Verificar API

GET http://127.0.0.1:5000/


# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------USUARIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

### Crear usuario

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Juan Perez",
    "nombre_usuario": "juan_perez_test",
    "correo": "juan.perez.test@nonnatest.com",
    "clave": "123456",
    "fecha_nacimiento": "2005-05-15"
}

















# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------NEGOCIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

###

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_negocio
Content-Type: application/json

{
    "id_usuario": "2",
    "nombre_comercial": "Nonna Enterprise",
    "descripcion": "adsfgwgrt",
    "logo": "",
    "portada": "",
    "telefono": "123456",
    "correo": "juan.perez.test@nonnatest.com",
    "sitio_web": "",
    "redes_sociales": ""
}

































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------EMPLEO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------













































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# --------------------------------MODERACION---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------













































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------RECETA.PY---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------



































