### Prueba inicial de Nonna

GET https://proyecto-anual-nonna-production.up.railway.app/

### Verificar API

GET http://127.0.0.1:5000/


# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------USUARIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

### Crear usuario

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Pablo",
    "nombre_usuario": "Blito",
    "correo": "Pabloncho@nonnatest.com",
    "clave": "12345678",
    "fecha_nacimiento": "2007-02-14"
}

### Iniciar sesion

















# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------NEGOCIO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

### Nuevo Negocio

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_negocio
Content-Type: application/json

{
    "id_usuario": "2",
    "nombre_comercial": "Nonna Enterprise",
    "descripcion": "adsfgwgrt",
    "logo": "",
    "portada": "",
    "telefono": "123456",
    "correo": "juan.perez.test@nonnatest.com",
    "sitio_web": "",
    "redes_sociales": ""
}


### Nueva Sucursal

POST https://proyecto-anual-nonna-production.up.railway.app/nueva_sucursal
Content-Type: application/json

{
    "id_negocio": "4",
    "nombre": "Nonna Enterprise Moreno",
    "direccion": "Osorio y Moreno 123",
    "horarios": "10:00 - 20:00",
    "casa_central": "0"
}

































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------EMPLEO---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------

### Nuevo empleo

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_empleo
Content-Type: application/json

{
    "id_negocio": "4",
    "id_sucursal": "1",
    "puesto": "Repositor",
    "descripcion": "Repositor con la capacidad de repositar repuestos",
    "jornada": "De 12:00 a 17:00",
    "vacantes": "1"
}


### Nuevo empleo en borrador

POST https://proyecto-anual-nonna-production.up.railway.app/nuevo_empleo_borrador
Content-Type: application/json

{
    "id_negocio": "4",
    "id_sucursal": "1",
    "puesto": "Cajero",
    "descripcion": "Cajero de 40 años de experiencia",
    "jornada": "De 10:00 a 17:00",
    "vacantes": "10"
}










































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# --------------------------------MODERACION---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------













































# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------
# ---------------------------------RECETA.PY---------------------------------------
# ----------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------



































